### ISSUE TITLE
example with nix-shell doesn't work

### ISSUE THREAD

**Issue by flip111** [thomashoneyman/purescript-halogen-portal#5]
nix shell comes online, spago starts building .. then at the end

```
[info] Installation complete.
Error found:
in module Halogen.Storybook
at .spago/halogen-storybook/master/src/Halogen/Storybook.purs:23:1 - 23:54 (line 23, column 1 - line 23, column 54)

  Module JSURI was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.


See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
or to contribute content related to this error.


[error] Failed to build.
```

**Comment by thomashoneyman** [comment]
Looks like the `packages.dhall` is pointing to the `master` branch of the Storybook library, but this library only supports projects on the 0.13.x compiler (I don't plan to maintain it anymore, but I'd accept a PR that brings it up to 0.15.x).

https://github.com/thomashoneyman/purescript-halogen-portal/blob/34bcb2bb1dd859749f2061479c74c6052519e115/packages.dhall#L9-L21

**Comment by flip111** [comment]
I'm going to close this because i removed support for nix in the latest version.
